#!/usr/bin/env sh
MODULE_NAME=`echo $1 | sed 's/\///g'`
BOT_TOKEN=$2
DATE=`date +%Y-%m-%d`
PACKAGE_NAME="${MODULE_NAME}_${DATE}"
EXCLUDES=`cat $MODULE_NAME/.gitignore | sed -e "s!^!--exclude=$MODULE_NAME/!" | tr '\n' ' '`
tar cvf $PACKAGE_NAME.tar $EXCLUDES --exclude=$MODULE_NAME/.git $MODULE_NAME/
gzip $PACKAGE_NAME.tar
curl -F document=@$PACKAGE_NAME.tar.gz https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=-100171218809
